// ============================================================
// Triangulate — PDF Export (Chunk 6.6)
// Generates PDF report from story data using @react-pdf/renderer
// ============================================================

import React from "react";
import { renderToBuffer, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  header: { marginBottom: 20 },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#666", marginBottom: 16 },
  divider: { borderBottomWidth: 1, borderBottomColor: "#e5e5e5", marginVertical: 12 },
  storyRow: { marginBottom: 14 },
  storyTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 3 },
  storyMeta: { fontSize: 9, color: "#555", marginBottom: 2 },
  convergenceHigh: { color: "#16a34a" },
  convergenceMid: { color: "#d97706" },
  convergenceLow: { color: "#dc2626" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#999", textAlign: "center" },
});

interface ExportStory {
  id: string;
  title: string;
  trustSignal: string;
  convergenceScore: number;
  articleCount: number;
  claimCount: number;
  biasTiers: string[];
  regions: string[];
  createdAt: string;
}

function convergenceStyle(score: number) {
  if (score >= 0.7) return styles.convergenceHigh;
  if (score >= 0.3) return styles.convergenceMid;
  return styles.convergenceLow;
}

function formatSignal(signal: string): string {
  return signal.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function TriangulatePDF({ stories }: { stories: ExportStory[] }) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return React.createElement(Document, null,
    React.createElement(Page, { size: "LETTER", style: styles.page },
      // Header
      React.createElement(View, { style: styles.header },
        React.createElement(Text, { style: styles.title }, "TRIANGULATE"),
        React.createElement(Text, { style: styles.subtitle },
          `Convergence Report \u2014 ${date} \u2014 ${stories.length} stories`
        ),
      ),
      React.createElement(View, { style: styles.divider }),
      // Stories
      ...stories.map((story) =>
        React.createElement(View, { key: story.id, style: styles.storyRow },
          React.createElement(Text, { style: styles.storyTitle }, story.title),
          React.createElement(Text, { style: styles.storyMeta },
            `${formatSignal(story.trustSignal)} \u00B7 ${story.articleCount} sources \u00B7 ${story.claimCount} claims \u00B7 ${story.regions.join(", ")}`
          ),
          React.createElement(Text, { style: [styles.storyMeta, convergenceStyle(story.convergenceScore)] },
            `Convergence: ${Math.round(story.convergenceScore * 100)}% \u00B7 Bias tiers: ${story.biasTiers.join(", ")}`
          ),
        )
      ),
      // Footer
      React.createElement(Text, { style: styles.footer },
        `Generated by Triangulate \u2014 www.triangulatenews.com \u2014 ${date}`
      ),
    )
  );
}

/**
 * Generate PDF buffer from story data.
 */
export async function generatePdfBuffer(stories: ExportStory[]): Promise<Buffer> {
  const doc = TriangulatePDF({ stories });
  return await renderToBuffer(doc as any);
}

/**
 * Trigger PDF download in the browser via blob URL.
 */
export function downloadPdf(buffer: ArrayBuffer, filename: string) {
  const blob = new Blob([buffer], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
